# Generated by Django 4.2.25 on 2025-10-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_status_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
