import { addIcons } from 'ionicons';
import {
  schoolOutline,
  baseballOutline,
  mailOutline,
  lockClosedOutline,
  personOutline,
  callOutline,
  personAddOutline,
  documentTextOutline,
  calendarOutline,
  cameraOutline,
  checkmarkOutline,
  createOutline,
  bookOutline,
  starOutline,
  saveOutline,
  eyeOutline,
  flashOutline,
  closeCircleOutline,
  alertCircleOutline,
  addOutline,
  ellipsisVertical,
  chevronForwardOutline,
  trashOutline,
  add,
  addCircle,
  homeOutline,
  peopleOutline,
  logOutOutline,
  personCircleOutline,
  cloudUploadOutline,
  folderOpenOutline,
  informationCircleOutline,
  closeOutline,
  documentOutline,
  easelOutline,
  downloadOutline,
  timeOutline,
} from 'ionicons/icons';

export function registerIcons() {
  addIcons({
    'school-outline': schoolOutline,
    'mail-outline': mailOutline,
    'lock-closed-outline': lockClosedOutline,
    'person-outline': personOutline,
    'call-outline': callOutline,
    'baseball-outline': baseballOutline,
    'person-add-outline': personAddOutline,
    'document-text-outline': documentTextOutline,
    'calendar-outline': calendarOutline,
    'camera-outline': cameraOutline,
    'checkmark-outline': checkmarkOutline,
    'create-outline': createOutline,
    'book-outline': bookOutline,
    'people-outline': peopleOutline,
    'star-outline': starOutline,
    'save-outline': saveOutline,
    'eye-outline': eyeOutline,
    'checkmark-circle-outline': checkmarkOutline,
    'flash-outline': flashOutline,
    'close-circle-outline': closeCircleOutline,
    'alert-circle-outline': alertCircleOutline,
    'add-outline': addOutline,
    'ellipsis-vertical': ellipsisVertical,
    'chevron-forward-outline': chevronForwardOutline,
    'trash-outline': trashOutline,
    add: add,
    'add-circle': addCircle,
    'home-outline': homeOutline,
    'log-out-outline': logOutOutline,
    ' person-circle-outline': personCircleOutline,
    'cloud-upload-outline':cloudUploadOutline,
    'folder-open-outline':folderOpenOutline,
    'information-circle-outline':informationCircleOutline,
    'close-outline': closeOutline,
    'document-outline':documentOutline,
    'easel-outline':easelOutline,
    'download-outline':downloadOutline,
    'time-outline':timeOutline,

  });
}
